# -*- coding: utf-8 -*-
"""OOP-1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ugJyISDpbFeXwhRDKZCjYhnYS87UVA7O
"""

class Personel:
    toplam_calisan = 0

    def __init__(self, ad, soyad, maas, kıdem):
        if maas < 0:
            raise ValueError("Maaş negatif olamaz.")
        if kıdem < 0:
            raise ValueError("Kıdem negatif olamaz.")

        self.ad = ad
        self.soyad = soyad
        self.maas = maas
        self.kıdem = kıdem
        Personel.toplam_calisan += 1

    def izin_hakki(self):
        if self.kıdem < 1:
            return 14
        elif 1 <= self.kıdem <= 5:
            return 20
        else:
            return 26

    def maas_artisi(self):
        if self.kıdem < 1:
            return self.maas * 1.05
        elif 1 <= self.kıdem <= 5:
            return self.maas * 1.10
        else:
            return self.maas * 1.15


    def izin_kullan(self,gun_sayisi):
      izin_hakki=self.izin_hakki()
      if gun_sayisi>izin_hakki:
        return f"Hata:Yetersiz izin hakkı!Toplam izin hakkınız:{izin_hakki}"
      else:
           return f"Kalan izin hakkınız: {izin_hakki - gun_sayisi} gün."





    def bilgigoster(self):
        print(f"Ad: {self.ad}")
        print(f"Soyad: {self.soyad}")
        print(f"Maaş: {self.maas} TL")
        print(f"Kıdem: {self.kıdem} yıl")
        print(f"İzin Hakkı: {self.izin_hakki()} gün")
        print(f"Yeni Maaş (Artış Dahil): {self.maas_artisi()} TL")

    @staticmethod
    def toplam_calisan_sayisi():
        return f"Toplam çalışan sayısı: {Personel.toplam_calisan}"

    def __str__(self):
        return f"{self.ad} {self.soyad}, Kıdem: {self.kıdem} yıl, Maaş: {self.maas} TL"


# Kullanım
calisan1 = Personel("Ali", "Yılmaz", 5478, 5)
calisan2 = Personel("Ayşe", "Kara", 6500, 2)
calisan3 = Personel("Mehmet", "Demir", 7200, 7)

print(calisan1.bilgigoster())
print(calisan2.izin_kullan(5))
print(Personel.toplam_calisan_sayisi())

